### ISSUE TITLE
Are request.params supposed to be encoded?

### ISSUE THREAD

**Issue by agentgt** [olivernn/davis.js#39]
It appears the parameters in request.params are already encoded. This is not what I was expecting.
Is this correct behavior?

That is if I post with a request parameter /blah?email=stuff@crap.com

```
request.param['email'] == stuff%40crap.com 
```

I expect:

```
request.param['email'] == stuff@crap.com
```

**Comment by agentgt** [comment]
The work around I did:

```
            var data = {};
            $.each(r.params, function(n, v) {
                data[n] = decodeURIComponent(v);
            });
```

**Comment by olivernn** [comment]
I think this could be due to the way that forms are serialised with jQuery, I'll take a closer look though because I thought this was being handled.  I think you should get your params in a non-urlencoded form though so this does sound like a bug.

**Comment by olivernn** [comment]
Fixed in the latest release, 0.9.0.

**Comment by mschulkind** [comment]
I'm on 0.9.0, but I'm still having this problem with spaces. decodeURIComponent() will not decode spaces that are encoded as '+' and a handful of other things. Do spaces work for you?

**Comment by olivernn** [comment]
Ah, sorry this isn't working for you.  I'll take a look and see if I can get this resolved once and for all.  Is it just the spaces as pluses that you are having problems with?  To help me fix this could you give me an example of the link/form paths that  causing the issue.

**Comment by mschulkind** [comment]
It's normal GET with a single type="text" name="q" parameter. I think more characters maybe be a problem, but I'm no expert, so this is how I solved it for now:

`query = URI(@raw.fullPath).query(true).q`

This is using the URI.js library, so I didn't have to worry about what else needs handling.

**Comment by olivernn** [comment]
Ok cool, I'll take a look and get a better fix out for this.

**Comment by olivernn** [comment]
Fixed in 0.9.1 - sorry for the delay!
